---
title: "Method For Acquiring and Comparing Spatially Explicit Measurements of Sun-induced Flourescence on the Ground"
subtitle: 'Discussion & Outlook'
output: 
    html_document:
        toc: true
        toc_depth: 4
        toc_float:
          collapsed: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The diurnal behaviour of SIF presents a challenge if one needs to characterize the spatial heterogeneity of SIF in the field which itself is subject to modulation through both structural and functional factors. We proposed a new SIF estimate, relative SIF, which (in certain aspects can correct) is unbiased of the diurnal development of sif. It is an estimate of the difference (distance) between SIF for a location relative to a baseline diurnal SIF from a reference device installed on a permanent reference position. In this way the contribution of SIF due to diurnal development can be decoupled and an estimate of SIF unaffected by time of the day between plots - calculated. The strenght of such apporach lies in preservation of the physical units as oposed to yield estimation. As such, a more mechanistic understanding of observed phenomenon (differences in SIF between plots) can be pirsuied.

So far, the ground based instruments adopted for SIF retrieval are designed to perform stationary measurements. The possibility do design smaller enough devices, and gimbal, opens new opportunity for collecting spatailly explicit SIF data over larger areas. such mobile apporach enables fast collection of data over larger areas, which, in combination with aditional auxilary sampling (e.g. chlorophyll, LAI),  provides observational data to study and understand the link between canopy biophysics and SIF in a larger area. Such mobile measurement approach is particularly suited for fast throughtput phenotyping of plant traits in controlled experimental field designs, where additional automation can be incorporated - such as installing the system on 4 wheel carriers.

This approach has several drawbacks which need to be mentioned. The Need for two intercalibrated devices introduces a level of uncertainty. It requires rigorous intercalibration and a sound observation matching. Next, selecting reference location will have enormous effects on the baseline which makes inter-study comparability of results more difficuilt. Most seriuos consideration is that this approach relies heavily on the assumption that the relative difference in SIF remains constant throughout the day. In other words the shape of the curve between different locations remains the same and one can be estimated from another through additive factor (linear relationship exists between two locations with different LAI), e.g. is dependent only on internal factors (e.g. structure). in other words there is a linear relationship between external factors and rSIF. While data supports such cliam it is logical to think that increas of incomming radiation does not linearly increase rSIF. These can be tested using simulation data. 

Alternative to the first drawback mentioned in previos paragraph is to replace the two device methodology with one device sandwitch measurement protocol in which diurnal reference and mobile measurements are preformed in two consecutive days. Provided that at least 2-3 day of stable atmospheric conditions are predicted and accepting assumption of comparability of SIF values between both dates this alternative can be particularly applicable in mediteranian region where more prolonged stable sunny days are prominent during summer. In this case the stationary diurnal reference measurements prior and post spatial measurements should be taken at the same location to infer about any short term changes in the behaviour in SIF. in fact, we performed such sandwitch measurement protocol on 1-3 august 2018 in sugar beet. The analysis can be seen in (Appendix or Web ?).

The specifics of the reference locations is an important consideration. For example, amount of biomass is the main factor determining the SIF quantity emitted per unit area. ideally, a preliminary visit will identify the variability in the field. In such way an average location (in terms of biomass and status) can be selected for the reference device. However, the arbitrary selection of reference location will always lead to unique and difficuilt to replicate experimental design.  

Replicate the same approach using SCOPE model to answer the following questions : Is rSIF really stable during the day or it changes with distance from solar noon? Is relative sif stable for across scales, species? Do results from modeling excersize confirm the field experiment? 
